title: 天外之音
description: てんがいのおと Voice of TATO
author: GamyongChang
permalink: /:title.html/
url: https://gamyongchang.github.io
paginate: 8
paginate_path: "/page:num"
repo: gamyongchang.github.io
owner: gamyongchang

markdown: redcarpet
redcarpet:
    extensions: ["tables"]
